### ISSUE TITLE
ModuleNotFoundError: No module named 'softgym'

### ISSUE THREAD

**Issue by sauravkambil** [DanielTakeshi/softgym_tfn#3] opened 2023-04-04 06:29 UTC
Hi all,

I recently started getting a ModuleNotFoundError on my softgym_tfn (public) and softagent_tfn - physical branch installations. 
I recently installed ROS on my system. Do you think this could be the cause?
For example:

```
(toolflownet) tmp@rchi-System-Product-Name:~/softgym_tfn$ python examples/random_env.py
Traceback (most recent call last):
  File "examples/random_env.py", line 7, in <module>
    from softgym.registered_env import env_arg_dict, SOFTGYM_ENVS
ModuleNotFoundError: No module named 'softgym'

```

```
(toolflownet) tmp@rchi-System-Product-Name:~/softagent_tfn$ python launch_exp.py
Number of experiment configurations:  1
exp_prefix:  BCphy_/home/tmp/softgym_tfn/data_demo/Toolflownet_ntrain_0080_PCL_PNet2_svd_pointwise_acttype_flow_rawPCL_scaleTarg
Traceback (most recent call last):
  File "/home/tmp/softagent_tfn/chester/run_exp_worker.py", line 13, in <module>
    from chester import config
ModuleNotFoundError: No module named 'chester'
```

I notice that an old post of @DanielTakeshi on the original softgym repo mentioned a similar error but this was fixed with updated paths. Link: https://github.com/Xingyu-Lin/softgym/issues/9#:~:text=(softgym)%20seita%40mason%3A~/softgym%20(master)%20%24%20python%20examples/random_env.py%20%2D%2Denv_name%20ClothFlatten%0ATraceback%20(most%20recent%20call%20last)%3A%0A%20%20File%20%22examples/random_env.py%22%2C%20line%205%2C%20in%20%3Cmodule%3E%0A%20%20%20%20from%20softgym.registered_env%20import%20env_arg_dict%2C%20SOFTGYM_ENVS%0AModuleNotFoundError%3A%20No%20module%20named%20%27softgym%27

Printing out my paths:
```
(toolflownet) tmp@rchi-System-Product-Name:~/softgym_tfn$ echo $PYFLEXROOT
/home/tmp/softgym_tfn/PyFlex
(toolflownet) tmp@rchi-System-Product-Name:~/softgym_tfn$ echo $PYTHONPATH
/opt/ros/melodic/lib/python2.7/dist-packages:/home/tmp/softgym_tfn/PyFlex/bindings/build
(toolflownet) tmp@rchi-System-Product-Name:~/softgym_tfn$ echo $LD_LIBRARY_PATH
/opt/ros/melodic/lib:/usr/local/cuda-11.3/lib64:/home/tmp/softgym_tfn/PyFlex/external/SDL2-2.0.4/lib/x64:/usr/local/cuda-11.3/lib64
(toolflownet) tmp@rchi-System-Product-Name:~/softgym_tfn$ echo $PATH
/opt/ros/melodic/bin:/usr/local/cuda-11.3/bin:/home/tmp/miniconda3/envs/toolflownet/bin:/usr/local/cuda-11.3/bin:/home/tmp/.local/bin:/usr/local/cuda-11.3/bin:/home/tmp/miniconda3/condabin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
```

Cuda Version:
```
(toolflownet) tmp@rchi-System-Product-Name:~/softagent_tfn$ nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2021 NVIDIA Corporation
Built on Mon_May__3_19:15:13_PDT_2021
Cuda compilation tools, release 11.3, V11.3.109
Build cuda_11.3.r11.3/compiler.29920130_0

(toolflownet) tmp@rchi-System-Product-Name:~/softagent_tfn$ nvidia-smi
Tue Apr  4 02:29:11 2023       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 530.30.02              Driver Version: 530.30.02    CUDA Version: 12.1     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                  Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf            Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA GeForce RTX 3060 Ti      On | 00000000:07:00.0 Off |                  N/A |
|  0%   34C    P8               20W / 200W|    566MiB /  8192MiB |      1%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
                                                                                         
+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
|    0   N/A  N/A      1215      G   /usr/lib/xorg/Xorg                           18MiB |
|    0   N/A  N/A      1330      G   /usr/bin/gnome-shell                         69MiB |
|    0   N/A  N/A      2572      G   /usr/lib/xorg/Xorg                          221MiB |
|    0   N/A  N/A      2779      G   /usr/bin/gnome-shell                         34MiB |
|    0   N/A  N/A      7534      G   /usr/lib/firefox/firefox                    133MiB |
|    0   N/A  N/A     13704      G   ...sion,SpareRendererForSitePerProcess       83MiB |
+---------------------------------------------------------------------------------------+

```

**Comment by SarthakJShetty** [comment] 2023-04-04 15:38
Hey @sauravkambil, can you use `python3` instead of `python`? ROS uses `python`, which is `python2` under the hood. This mostly isn't the issue, but doesn't hurt to try. If you could also post the output of running `python --version`, that would help. Thanks!

**Comment by sauravkambil** [comment] 2023-04-04 15:43
Hi, @SarthakJShetty thanks for the response.

Sure, here is the output of that:

```
(toolflownet) tmp@rchi-System-Product-Name:~/softagent_tfn$ python3 launch_exp.py
Number of experiment configurations:  1
exp_prefix:  BCphy_/home/tmp/softgym_tfn/data_demo/Toolflownet_ntrain_0080_PCL_PNet2_svd_pointwise_acttype_flow_rawPCL_scaleTarg
Traceback (most recent call last):
  File "/home/tmp/softagent_tfn/chester/run_exp_worker.py", line 13, in <module>
    from chester import config
ModuleNotFoundError: No module named 'chester'
(toolflownet) tmp@rchi-System-Product-Name:~/softagent_tfn$ cd ..
(toolflownet) tmp@rchi-System-Product-Name:~$ cd ./softgym_tfn
(toolflownet) tmp@rchi-System-Product-Name:~/softgym_tfn$ python3 examples/random_env.py
Traceback (most recent call last):
  File "examples/random_env.py", line 7, in <module>
    from softgym.registered_env import env_arg_dict, SOFTGYM_ENVS
ModuleNotFoundError: No module named 'softgym'
(toolflownet) tmp@rchi-System-Product-Name:~/softgym_tfn$ python --version
Python 3.7.13
```

**Comment by SarthakJShetty** [comment] 2023-04-15 15:41
Seems like @sauravkambil managed to fix this. It was due to a `$PATH` variable change caused by a new ROS installation. Closing for now. Thanks!

**Closed as completed by SarthakJShetty** 2023-04-15 15:41 UTC
